defaults: &npm_steps
  - checkout
  - restore_cache:
      keys:
        - npm
  - run: npm install
  - save_cache:
      key: npm
      paths:
        - ./node_modules
  
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      <<: *npm_steps
      - run: npm run compile
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      <<: *npm_steps
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8
        environment:
          - PGHOST: 127.0.0.1
          - PGUSER: postgres
      - image: circleci/postgres:9
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: postgres
    steps:
      - checkout
      <<: *npm_steps
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
      - test
