version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm
      - run: npm install
      - save_cache:
          key: npm
          paths:
            "~/.npm"
      - run: npm run compile
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm
      - run: npm install
      - save_cache:
          key: npm
          paths:
            "~/.npm"
      - run: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
