version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
        - npm install
        - npm run compile
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        - npm install
        - npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
