version: 2

defaults: &npm_steps
  steps:
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - restore_cache:
        key: npm-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: npm-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
jobs:
  lint:
    docker:
      - image: circleci/node:8
    <<: *npm_steps
    steps+:
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8
        environment:
          - PGHOST: 127.0.0.1
          - PGUSER: postgres
      - image: circleci/postgres:9
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: postgres
    <<: *npm_steps
    steps+:
      - run: npm test
  publish:
    docker:
      - image: circleci/node:8
    <<: *npm_steps
    steps+:
      - run: npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint
      - test
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: v*
